# Generated by Django 5.2.4 on 2025-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='My Name', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='my name', max_length=100),
            preserve_default=False,
        ),
    ]
