# Generated by Django 5.2.4 on 2025-07-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='work_images/')),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('uiux', 'UI/UX Design'), ('data', 'Data Science'), ('mobile', 'Mobile App')], max_length=50)),
            ],
        ),
    ]
