# Generated by Django 5.2.4 on 2025-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools'), ('programming', 'Programming Languages')], max_length=20)),
                ('image', models.ImageField(upload_to='skill_images/')),
            ],
        ),
    ]
