# Generated by Django 5.2.4 on 2025-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='title',
        ),
    ]
